import React from 'react';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="flex-1 bg-navy-950 bg-grid-pattern py-12 md:py-20 select-text">
      <div className="mx-auto max-w-3xl px-6 space-y-8">
        
        {/* Navigation Breadcrumb */}
        <div className="mb-6 border-b border-navy-800/60 pb-5">
          <Link 
            href="/"
            className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-400 hover:text-white transition-colors group"
          >
            ← Back to Home
          </Link>
          <h1 className="text-3xl font-extrabold text-white tracking-tight mt-2">
            Terms of Use
          </h1>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Effective Date: June 8, 2026 &bull; Last Updated: June 8, 2026
          </p>
        </div>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">1. Acceptance of Terms</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            By accessing or using Vurdict at{" "}
            <a href="https://vurdict.vercel.app" target="_blank" rel="noopener noreferrer" className="text-indigo-400 font-medium hover:underline">
              vurdict.vercel.app
            </a>{" "}
            (“the Service”), you agree to be bound by these Terms of Use. If you do not agree, do not use the Service.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">2. What Vurdict Is</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            Vurdict is an AI-powered tool that analyzes publicly accessible design portfolio case studies and returns structured, scored feedback based on a defined evaluation framework.
          </p>
          <p className="text-sm text-slate-300 leading-relaxed font-semibold pt-2">Vurdict is not:</p>
          <ul className="list-disc pl-5 space-y-2 text-sm text-slate-300">
            <li>A professional career advisory service</li>
            <li>A guarantee of employment or freelance success</li>
            <li>A substitute for feedback from human hiring managers, design leads, or industry professionals</li>
            <li>A definitive measure of your value or ability as a designer</li>
          </ul>
          <p className="text-sm text-slate-300 leading-relaxed pt-2">
            Scores and feedback are generated by an AI model and reflect the content of your submitted case study at the time of analysis. They are meant to be useful starting points, not final verdicts.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">3. Acceptable Use</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            You agree to use Vurdict only for lawful purposes. You must not:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-sm text-slate-300">
            <li>Submit URLs designed to harm, exploit, or test the security of our systems</li>
            <li>Attempt to reverse-engineer, scrape, or replicate Vurdict’s evaluation pipeline</li>
            <li>Submit case studies that contain content that is illegal, harmful, or violates third-party rights</li>
            <li>Use the Service to generate feedback for commercial resale without our written permission</li>
            <li>Misrepresent Vurdict’s scores as official assessments or professional certifications</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">4. Intellectual Property</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            The Vurdict name, logo, design system, evaluation framework, and all associated content are owned by Vurdict. You may not reproduce, distribute, or create derivative works from any part of the Service without written permission.
          </p>
          <p className="text-sm text-slate-300 leading-relaxed">
            The feedback and report generated from your case study is yours to use, share, and act on freely.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">5. Disclaimer of Warranties</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            The Service is provided “as is” and “as available” without warranties of any kind, express or implied. We do not warrant that:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-sm text-slate-300">
            <li>The Service will be uninterrupted or error-free</li>
            <li>AI-generated scores will be accurate, complete, or suitable for any specific purpose</li>
            <li>The Service will be compatible with all portfolio platforms or URL types</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">6. Limitation of Liability</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            To the fullest extent permitted by applicable law, Vurdict shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to reliance on AI-generated feedback in employment or business decisions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">7. Third-Party Services</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            Vurdict uses third-party services including Jina Reader, Google Gemini API, and Vercel to deliver its functionality. We are not responsible for the availability, accuracy, or conduct of these services.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">8. Changes to the Service</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            We reserve the right to modify, suspend, or discontinue any part of the Service at any time without notice. We may also update these Terms. Continued use of the Service after changes constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">9. Governing Law</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes arising from these Terms shall be subject to the jurisdiction of Nigerian courts.
          </p>
        </section>

        <section className="space-y-4 border-t border-navy-800/60 pt-6">
          <h2 className="text-lg font-bold text-white uppercase tracking-wider">10. Contact</h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            For questions about these Terms:{" "}
            <a href="mailto:vurdict@gmail.com" className="text-indigo-400 font-semibold hover:underline">
              vurdict@gmail.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
