import React from 'react';
import { useNavigate, Link } from 'react-router-dom';
import Logo from '../components/Logo';

export default function TermsPage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-white text-slate-900 flex flex-col justify-between select-none font-sans relative overflow-x-hidden">
      {/* Header */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/95 backdrop-blur-lg h-16 px-6 md:px-12 border-b border-slate-100 flex items-center">
        <div className="max-w-7xl w-full mx-auto flex items-center justify-between">
          <Logo onClick={() => navigate('/')} />
          <button
            onClick={() => navigate('/')}
            className="text-xs font-normal text-slate-500 hover:text-brand-900 transition-colors flex items-center gap-1.5 cursor-pointer whitespace-nowrap shrink-0"
          >
            <span>← Back to Home</span>
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 max-w-3xl w-full mx-auto px-6 py-24 md:py-32 text-center space-y-8 select-text">
        <div className="space-y-2 border-b border-slate-100 pb-6">
          <h1 className="text-3xl font-bold text-slate-950 tracking-tight">Terms of Use</h1>
          <p className="text-xs text-slate-400 font-medium">
            Effective Date: June 8, 2026 &bull; Last Updated: June 8, 2026
          </p>
        </div>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-slate-900 mt-6 uppercase tracking-wider">1. Acceptance of Terms</h2>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            By accessing or using Vurdict at{" "}
            <a href="https://vurdict.vercel.app" target="_blank" rel="noopener noreferrer" className="text-brand-900 font-medium hover:underline">
              vurdict.vercel.app
            </a>{" "}
            (“the Service”), you agree to be bound by these Terms of Use. If you do not agree, do not use the Service.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-slate-900 mt-6 uppercase tracking-wider">2. What Vurdict Is</h2>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            Vurdict is an AI-powered tool that analyzes publicly accessible design portfolio case studies and returns structured, scored feedback based on a defined evaluation framework.
          </p>
          <p className="text-sm text-slate-600 leading-relaxed font-normal font-semibold pt-2">Vurdict is not:</p>
          <ul className="list-none space-y-2 text-sm text-slate-600 font-normal">
            <li>&mdash; A professional career advisory service</li>
            <li>&mdash; A guarantee of employment or freelance success</li>
            <li>&mdash; A substitute for feedback from human hiring managers, design leads, or industry professionals</li>
            <li>&mdash; A definitive measure of your value or ability as a designer</li>
          </ul>
          <p className="text-sm text-slate-600 leading-relaxed font-normal pt-2">
            Scores and feedback are generated by an AI model and reflect the content of your submitted case study at the time of analysis. They are meant to be useful starting points, not final verdicts.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-slate-900 mt-6 uppercase tracking-wider">3. Acceptable Use</h2>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            You agree to use Vurdict only for lawful purposes. You must not:
          </p>
          <ul className="list-none space-y-2 text-sm text-slate-600 font-normal">
            <li>&mdash; Submit URLs designed to harm, exploit, or test the security of our systems</li>
            <li>&mdash; Attempt to reverse-engineer, scrape, or replicate Vurdict’s evaluation pipeline</li>
            <li>&mdash; Submit case studies that contain content that is illegal, harmful, or violates third-party rights</li>
            <li>&mdash; Use the Service to generate feedback for commercial resale without our written permission</li>
            <li>&mdash; Misrepresent Vurdict’s scores as official assessments or professional certifications</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-slate-900 mt-6 uppercase tracking-wider">4. Intellectual Property</h2>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            The Vurdict name, logo, design system, evaluation framework, and all associated content are owned by Vurdict. You may not reproduce, distribute, or create derivative works from any part of the Service without written permission.
          </p>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            The feedback and report generated from your case study is yours to use, share, and act on freely.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-slate-900 mt-6 uppercase tracking-wider">5. Disclaimer of Warranties</h2>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            The Service is provided “as is” and “as available” without warranties of any kind, express or implied. We do not warrant that:
          </p>
          <ul className="list-none space-y-2 text-sm text-slate-600 font-normal">
            <li>&mdash; The Service will be uninterrupted or error-free</li>
            <li>&mdash; AI-generated scores will be accurate, complete, or suitable for any specific purpose</li>
            <li>&mdash; The Service will be compatible with all portfolio platforms or URL types</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-slate-900 mt-6 uppercase tracking-wider">6. Limitation of Liability</h2>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            To the fullest extent permitted by applicable law, Vurdict shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to reliance on AI-generated feedback in employment or business decisions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-slate-900 mt-6 uppercase tracking-wider">7. Third-Party Services</h2>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            Vurdict uses third-party services including Jina Reader, Google Gemini API, and Vercel to deliver its functionality. We are not responsible for the availability, accuracy, or conduct of these services.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-slate-900 mt-6 uppercase tracking-wider">8. Changes to the Service</h2>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            We reserve the right to modify, suspend, or discontinue any part of the Service at any time without notice. We may also update these Terms. Continued use of the Service after changes constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-slate-900 mt-6 uppercase tracking-wider">9. Governing Law</h2>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes arising from these Terms shall be subject to the jurisdiction of Nigerian courts.
          </p>
        </section>

        <section className="space-y-4 border-t border-slate-100 pt-6">
          <h2 className="text-lg font-bold text-slate-900 uppercase tracking-wider">10. Contact</h2>
          <p className="text-sm text-slate-600 leading-relaxed font-normal">
            For questions about these Terms:{" "}
            <a href="mailto:hellovurdict@gmail.com" className="text-brand-900 font-semibold hover:underline">
              hellovurdict@gmail.com
            </a>
          </p>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-100 py-8 bg-white text-slate-500 z-10 shrink-0">
        <div className="max-w-7xl w-full mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex flex-col items-center md:items-start gap-1">
            <div className="flex items-center">
              <Logo size="small" />
            </div>
            <p className="text-[10px] text-slate-400 font-medium mt-1">
              &copy; 2026 Vurdict. The Reviewer's Perspective.
            </p>
          </div>
          <div className="flex gap-6 text-xs font-normal text-slate-500">
            <Link to="/privacy" className="hover:text-brand-900 transition-colors">Privacy Policy</Link>
            <Link to="/terms" className="hover:text-brand-900 transition-colors">Terms of Use</Link>
            <Link to="/support" className="hover:text-brand-900 transition-colors">Support Us</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
